title: "Repositorio de proyectos – Armando Rodríguez"
description: "Portafolio de proyectos de IA, visión y robótica."
theme: jekyll-theme-cayman   # (también funcionan 'minimal', 'slate', 'time-machine', etc.)
show_downloads: false
github:
  is_project_page: true
