title: "Proyectos de Inteligencia Artificial – Armando Rodríguez"
description: "Repositorio y portafolio de proyectos de IA, ML y análisis de datos."
theme: jekyll-theme-cayman
show_downloads: false
github:
  is_project_page: true
