title: "Proyectos de Inteligencia Artificial – Armando Rodríguez"
description: "Repositorio y portafolio de proyectos de Inteligencia Artificial, Control, Visión Computacional y Robótica."
theme: jekyll-theme-cayman
baseurl: "/ProyectosArmandoRdz"
show_downloads: false
github:
  is_project_page: false
